---
title: "Handreiking"
subtitle: "Bijdragen aan GO FAIR_GOV_NL"
---


## Hoe we werken op Github

We hanteren een open source aanpak op Github. Dit waarborgt een open en transparante werkwijzen en maakt het eenvoudig om versiebeheer op GO FAIR_GOV_NL toe te passen. We werken voor de content met [Markdown](https://quarto.org/docs/authoring/markdown-basics.html) bestanden. Dit is een bestandsformaat voor platte tekstbestanden en wordt door veel verschillende tools ondersteund. Daarnaast maken we gebruik van [Quarto](https://quarto.org/) om vanuit de Markdown bestanden deze website te genereren.



## Stel een vraag

Heb je een vraag? Er zijn verschillende manieren waarop je een vraag kunt stellen. 


### Maak op GitHub een issue aan

Maak op GitHub een [Issue](https://github.com/gofair-foundation/gofair-wiki-gov-nl/issues) aan. 

1. Klik op de knop "New issue".
2. Schrijf je vraag of opmerking kort op en geef daaronder een toelichting.
3. Klik op de knop "Create"
4. Anderen kunnen daarna eventueel nog opmerkingen toevoegen aan jouw issue.


### Stel je vraag via mail

Je kunt je vraag ook stellen door een mail te sturen naar **[]()**.


## Meld een fout

Heb je een fout gevonden?


### Maak op GitHub een issue aan

Maak op GitHub een [Issue](https://github.com/gofair-foundation/gofair-wiki-gov-nl/issues) aan. 

1. Klik op de knop "New issue".
2. Omschrijf de fout kort en geef daaronder een toelichting.
3. Klik op de knop "Create"
4. Anderen kunnen daarna eventueel nog opmerkingen toevoegen aan jouw issue.

   
## Stel een wijziging voor

Heb je een suggestie of wil je een verbetering voorstellen? Er zijn verschillende manieren waarop je een verbetering kunt voorstellen. 


### Maak op GitHub een issue aan

Maak op GitHub een [Issue](https://github.com/gofair-foundation/gofair-wiki-gov-nl/issues) aan.

1. Klik op de knop "New issue".
2. Schrijf je suggestie kort op en geef daaronder een toelichting.
3. Klik op de knop "Create"
4. Anderen kunnen daarna eventueel nog opmerkingen toevoegen aan jouw issue.


### Maak op GitHub een pull-request aan

Kun je niet uit de voeten met een issue bijvoorbeeld omdat je een omvangrijk wijzigingsvoorstel wilt doen? Dan kun je in een eigen GitHub account een [Fork](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks) van de repository van GO FAIR_GOV_NL maken en daarvandaan een [Pull Request](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks) doen.





