---
title: "FAIR Guiding Principles"
subtitle: "Een Nederlands profiel door en voor de Nederlandse overheid"
---

### Vindbaarheid

Onder vindbaarheid wordt hier verstaan de mate waarin data en metadata eenvoudig gevonden kunnen worden door mensen en machines.


------------------------------------------------------------------------

#### F1

**Principe**

Aan (meta)data worden een wereldwijd unieke en permanente identificatiecode toegevoegd

**Interpretatie**

De interpretatie van dit principe door en voor de Nederlandse overheid

**Implementatie**

Een beschrijving van conceptuele bouwstenen of [Architecture Building Block(s)](https://pubs.opengroup.org/architecture/togaf8-doc/arch/chap32.html) volgens TOGAF die dit principe implementeren.

**Realisatie**

Een beschrijving van concrete bouwstenen of [Solution Building Block(s)](https://pubs.opengroup.org/architecture/togaf8-doc/arch/chap32.html) volgens TOGAF, die de genoemde Architecture Building Block(s) realiseren.

[SURF](https://www.surf.nl/en/services/persistent-identifiers "SURF") [DOI](https://www.doi.org/ "DOI")

------------------------------------------------------------------------

#### F2

**Principe**

Data worden beschreven met rijke metadata

**Interpretatie**

De interpretatie van dit principe door en voor de Nederlandse overheid

**Implementatie**

Een beschrijving van conceptuele bouwstenen of [Architecture Building Block(s)](https://pubs.opengroup.org/architecture/togaf8-doc/arch/chap32.html) volgens TOGAF die dit principe implementeren.

**Realisatie**

Een beschrijving van concrete bouwstenen of [Solution Building Block(s)](https://pubs.opengroup.org/architecture/togaf8-doc/arch/chap32.html) volgens TOGAF, die de genoemde Architecture Building Block(s) realiseren.


------------------------------------------------------------------------

#### F3

**Principe**

Metadata bevatten duidelijk en expliciet de identificatie van de data die ze beschrijven

**Interpretatie**

De interpretatie van dit principe door en voor de Nederlandse overheid

**Implementatie**

Een beschrijving van conceptuele bouwstenen of [Architecture Building Block(s)](https://pubs.opengroup.org/architecture/togaf8-doc/arch/chap32.html) volgens TOGAF die dit principe implementeren.

**Realisatie**

Een beschrijving van concrete bouwstenen of [Solution Building Block(s)](https://pubs.opengroup.org/architecture/togaf8-doc/arch/chap32.html) volgens TOGAF, die de genoemde Architecture Building Block(s) realiseren.


------------------------------------------------------------------------

#### F4

**Principe**

(Meta)data worden geregistreerd of geïndexeerd in een doorzoekbare bron

**Interpretatie**

De interpretatie van dit principe door en voor de Nederlandse overheid

**Implementatie**

Een beschrijving van conceptuele bouwstenen of [Architecture Building Block(s)](https://pubs.opengroup.org/architecture/togaf8-doc/arch/chap32.html) volgens TOGAF die dit principe implementeren.

**Realisatie**

Een beschrijving van concrete bouwstenen of [Solution Building Block(s)](https://pubs.opengroup.org/architecture/togaf8-doc/arch/chap32.html) volgens TOGAF, die de genoemde Architecture Building Block(s) realiseren.


------------------------------------------------------------------------

### Toegankelijkheid

------------------------------------------------------------------------

#### A1

**Principe**

(Meta)data zijn opvraagbaar op basis van hun identificatiecode met behulp van een gestandaardiseerd communicatieprotocol

**Interpretatie**

De interpretatie van dit principe door en voor de Nederlandse overheid

**Implementatie**

Een beschrijving van conceptuele bouwstenen of [Architecture Building Block(s)](https://pubs.opengroup.org/architecture/togaf8-doc/arch/chap32.html) volgens TOGAF die dit principe implementeren.

**Realisatie**

Een beschrijving van concrete bouwstenen of [Solution Building Block(s)](https://pubs.opengroup.org/architecture/togaf8-doc/arch/chap32.html) volgens TOGAF, die de genoemde Architecture Building Block(s) realiseren.


------------------------------------------------------------------------

#### A1.1

**Principe**

Het protocol is open, vrij en universeel implementeerbaar

**Interpretatie**

De interpretatie van dit principe door en voor de Nederlandse overheid

**Implementatie**

Een beschrijving van conceptuele bouwstenen of [Architecture Building Block(s)](https://pubs.opengroup.org/architecture/togaf8-doc/arch/chap32.html) volgens TOGAF die dit principe implementeren.

**Realisatie**

Een beschrijving van concrete bouwstenen of [Solution Building Block(s)](https://pubs.opengroup.org/architecture/togaf8-doc/arch/chap32.html) volgens TOGAF, die de genoemde Architecture Building Block(s) realiseren.


------------------------------------------------------------------------

#### A1.2

**Principe**

Het protocol maakt waar nodig een authenticatie- en autorisatieprocedure mogelijk

**Interpretatie**

De interpretatie van dit principe door en voor de Nederlandse overheid

**Implementatie**

Een beschrijving van conceptuele bouwstenen of [Architecture Building Block(s)](https://pubs.opengroup.org/architecture/togaf8-doc/arch/chap32.html) volgens TOGAF die dit principe implementeren.

**Realisatie**

Een beschrijving van concrete bouwstenen of [Solution Building Block(s)](https://pubs.opengroup.org/architecture/togaf8-doc/arch/chap32.html) volgens TOGAF, die de genoemde Architecture Building Block(s) realiseren.


------------------------------------------------------------------------

#### A2

**Principe**

Metadata zijn toegankelijk, ook als de data niet meer beschikbaar zijn

**Interpretatie**

De interpretatie van dit principe door en voor de Nederlandse overheid

**Implementatie**

Een beschrijving van conceptuele bouwstenen of [Architecture Building Block(s)](https://pubs.opengroup.org/architecture/togaf8-doc/arch/chap32.html) volgens TOGAF die dit principe implementeren.

**Realisatie**

Een beschrijving van concrete bouwstenen of [Solution Building Block(s)](https://pubs.opengroup.org/architecture/togaf8-doc/arch/chap32.html) volgens TOGAF, die de genoemde Architecture Building Block(s) realiseren.


------------------------------------------------------------------------

### Interoperabiliteit

------------------------------------------------------------------------

#### I1

**Principe**

(Meta)data gebruiken een formele, toegankelijke, gedeelde en breed toepasbare taal voor kennisrepresentatie

**Interpretatie**

De interpretatie van dit principe door en voor de Nederlandse overheid

**Implementatie**

Een beschrijving van conceptuele bouwstenen of [Architecture Building Block(s)](https://pubs.opengroup.org/architecture/togaf8-doc/arch/chap32.html) volgens TOGAF die dit principe implementeren.

**Realisatie**

Een beschrijving van concrete bouwstenen of [Solution Building Block(s)](https://pubs.opengroup.org/architecture/togaf8-doc/arch/chap32.html) volgens TOGAF, die de genoemde Architecture Building Block(s) realiseren.


------------------------------------------------------------------------

#### I2

**Principe**

(Meta)data gebruiken gegevenswoordenboeken of vocabulaires die FAIR-principes volgen

**Interpretatie**

De interpretatie van dit principe door en voor de Nederlandse overheid

**Implementatie**

Een beschrijving van conceptuele bouwstenen of [Architecture Building Block(s)](https://pubs.opengroup.org/architecture/togaf8-doc/arch/chap32.html) volgens TOGAF die dit principe implementeren.

**Realisatie**

Een beschrijving van concrete bouwstenen of [Solution Building Block(s)](https://pubs.opengroup.org/architecture/togaf8-doc/arch/chap32.html) volgens TOGAF, die de genoemde Architecture Building Block(s) realiseren.


------------------------------------------------------------------------

#### I3

**Principe**

(Meta)data bevatten gekwalificeerde verwijzingen naar andere (meta)data

**Interpretatie**

De interpretatie van dit principe door en voor de Nederlandse overheid

**Implementatie**

Een beschrijving van conceptuele bouwstenen of [Architecture Building Block(s)](https://pubs.opengroup.org/architecture/togaf8-doc/arch/chap32.html) volgens TOGAF die dit principe implementeren.

**Realisatie**

Een beschrijving van concrete bouwstenen of [Solution Building Block(s)](https://pubs.opengroup.org/architecture/togaf8-doc/arch/chap32.html) volgens TOGAF, die de genoemde Architecture Building Block(s) realiseren.


------------------------------------------------------------------------

### Herbruikbaarheid

------------------------------------------------------------------------

#### R1

**Principe**

(Meta)data worden rijkelijk beschreven met een veelheid aan nauwkeurige en relevante attributen

**Interpretatie**

De interpretatie van dit principe door en voor de Nederlandse overheid

**Implementatie**

Een beschrijving van conceptuele bouwstenen of [Architecture Building Block(s)](https://pubs.opengroup.org/architecture/togaf8-doc/arch/chap32.html) volgens TOGAF die dit principe implementeren.

**Realisatie**

Een beschrijving van concrete bouwstenen of [Solution Building Block(s)](https://pubs.opengroup.org/architecture/togaf8-doc/arch/chap32.html) volgens TOGAF, die de genoemde Architecture Building Block(s) realiseren.


------------------------------------------------------------------------

#### R1.1

**Principe**

(Meta)data worden vrijgegeven met een duidelijke en toegankelijke licentie voor datagebruik

**Interpretatie**

De interpretatie van dit principe door en voor de Nederlandse overheid

**Implementatie**

Een beschrijving van conceptuele bouwstenen of [Architecture Building Block(s)](https://pubs.opengroup.org/architecture/togaf8-doc/arch/chap32.html) volgens TOGAF die dit principe implementeren.

**Realisatie**

Een beschrijving van concrete bouwstenen of [Solution Building Block(s)](https://pubs.opengroup.org/architecture/togaf8-doc/arch/chap32.html) volgens TOGAF, die de genoemde Architecture Building Block(s) realiseren.


------------------------------------------------------------------------

#### R1.2

**Principe**

(Meta)data worden geassocieerd met gedetailleerde herkomst

**Interpretatie**

De interpretatie van dit principe door en voor de Nederlandse overheid

**Implementatie**

Een beschrijving van conceptuele bouwstenen of [Architecture Building Block(s)](https://pubs.opengroup.org/architecture/togaf8-doc/arch/chap32.html) volgens TOGAF die dit principe implementeren.

**Realisatie**

Een beschrijving van concrete bouwstenen of [Solution Building Block(s)](https://pubs.opengroup.org/architecture/togaf8-doc/arch/chap32.html) volgens TOGAF, die de genoemde Architecture Building Block(s) realiseren.


------------------------------------------------------------------------

#### R1.3

**Principe**

(Meta)data voldoen aan domein-relevante normen

**Interpretatie**

De interpretatie van dit principe door en voor de Nederlandse overheid

**Implementatie**

Een beschrijving van conceptuele bouwstenen of [Architecture Building Block(s)](https://pubs.opengroup.org/architecture/togaf8-doc/arch/chap32.html) volgens TOGAF die dit principe implementeren.

**Realisatie**

Een beschrijving van concrete bouwstenen of [Solution Building Block(s)](https://pubs.opengroup.org/architecture/togaf8-doc/arch/chap32.html) volgens TOGAF, die de genoemde Architecture Building Block(s) realiseren.


------------------------------------------------------------------------

### Bronnen


  “FAIR.” GO FAIR Foundation, https://www.gofair.foundation/interpretation. Accessed 9 Jan. 2025.

  Jacobsen, Annika, et al. “FAIR Principles: Interpretations and Implementation Considerations.” *Data Intelligence*, vol. 2, no. 1–2, 2020, pp. 10–29, https://doi.org/10.1162/dint_r_00024.

  Research Data Alliance FAIR Data Maturity Model Working Group. FAIR Data Maturity Model: Specification and Guidelines. 2020, https://doi.org/10.15497/RDA00050.
  
  FAIR Vocabulary. https://peta-pico.github.io/FAIR-nanopubs/principles/index-en.html#https://w3id.org/fair/principles/terms/F. Accessed 9 Jan. 2025.
  
  TOGAF



